name: Test Action for Multiple Files
description: What it says on the tin.

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: axodotdev/sarah-action/.github/workflows/one-a@two-parter
    - name: Log event name
      run: echo Hello, {{ $inputs.event_name }}!
      shell: bash
