name: Test Action for Multiple Files
description: What it says on the tin.

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    # - name: Dump GitHub context
    #   id: github_context_step
    #   run: echo '${{ toJSON(github) }}'
    #   shell: bash
    # - name: Dump job context
    #   run: echo '${{ toJSON(job) }}'
    #   shell: bash
    # - name: Dump steps context
    #   run: echo '${{ toJSON(steps) }}'
    #   shell: bash
    # - name: Dump runner context
    #   run: echo '${{ toJSON(runner) }}'
    #   shell: bash
    # - name: Dump strategy context
    #   run: echo '${{ toJSON(strategy) }}'
    #   shell: bash
    # - name: Dump matrix context
    #   run: echo '${{ toJSON(matrix) }}'
    #   shell: bash
    - uses: actions/checkout@v3
    - uses: axodotdev/sarah-action/one-a@main
      with:
        event_name: ${{ inputs.event_name }}
