# This is a workflow to mimic the structures we are investigating
# with correct access levels and packaging possibilities.

name: one-a

# on:
#   workflow_call:
#     inputs:
#       event-name:
#         required: true
#         type: string

jobs:
  build:
    # Given action, just nice as a reminder for now
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # Check that it's a PR triggered action
  # label-pull:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just a check
  #       run: echo ${{ inputs.event_name }}

  # call-one-b:
  #   # One of three job triggers for the big file (one-b)
  #   uses: axodotdev/sarah-action/one-b@main
  #   with:
  #     config-word: moon
