# This is a workflow to mimic the structures we are investigating
# with correct access levels and packaging possibilities.

name: one-a

runs:
  using: "composite"

  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
      shell: bash

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
      shell: bash
