# Attempt to call from API
name: one-c

on:
  workflow_dispatch:
    inputs:
      config-phrase:
        required: false
        type: string
        default: anteater


jobs:
  dispatches-happen:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatches happen
        run: echo Hello, dispatches, from ${{ inputs.config-phrase }}!
